language: ruby

sudo: required
cache: bundler

services:
 - mysql

dist: trusty

before_install:
  - jdk_switcher use openjdk8
  - ./.travis-install-dependencies.sh

notifications:
  email:
    - kill-bill-commits@googlegroups.com

rvm:
  - 2.2.2
  # Until new KPM is released
  #- 2.4.0
  #- jruby-9.1.12.0
  #- ruby-head
  #- jruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
    - rvm: jruby-head
